### PR TITLE
#163062438 Build test for the user

### PR DESCRIPTION
**Pull request by Bakley**
#### What does this PR do?
- Have the user test
#### Description of Task to be completed?
- Test user signup 
- Test user login

#### Any background context you want to provide?
- Using TDD to guide my app
#### What are the relevant pivotal tracker stories?
#163062438

### CODE REVIEW

**Comment by SolomonMacharia** [comment]
Nice. Can it be tested manually?

**Comment by cod3smith** [comment]
How can you manually test it?

**Comment by JosephNjuguna** [comment]
nice
did the test pass in  travisci??
send screenshot

**Comment by Bakley** [comment]
No, the test failed because I don't have any code yet, I am using the TDD approach

**Pull request merged**
